// ========================================
// SERVER CONFIGURATION
// Centralized constants for server-authoritative game logic
// (Anti-cheat: ignore client values, use these)
// ========================================
const SERVER_CONFIG = {
    // World
    WORLD: {
        WIDTH: 1920,
        HEIGHT: 1080,
    },

    // Team
    TEAM: {
        RED: 'red',
        BLUE: 'blue',
        MAX_PLAYERS_PER_TEAM: 5,
    },

    // Player
    PLAYER: {
        SPEED: 300,                     // pixels per second
        SPEED_TOLERANCE: 1.5,           // Allow 50% variance for network latency
        MAX_HP: 100,
        RESPAWN_DELAY_MS: 3000,         // 3 seconds
        RESPAWN_X: 960,                 // Center of game world
        RESPAWN_Y: 540,
    },

    // Combat
    COMBAT: {
        ATTACK_POWER: 10,
        ATTACK_RANGE: 150,
        ATTACK_COOLDOWN_MS: 500,
        HIT_RADIUS: 67.5,               // Half of character size for collision
    },

    // Knockback
    KNOCKBACK: {
        MIN_DISTANCE: 30,
        MAX_DISTANCE: 100,
        MULTIPLIER_MIN: 1.25,
        MULTIPLIER_MAX: 2.5,
        BOUNDARY_MARGIN: 50,
        LASER_DISTANCE: 50,             // Fixed knockback for laser
    },

    // Skill - Laser (Q)
    SKILL_LASER: {
        DAMAGE: 44,
        MAX_LENGTH: 2000,
        COOLDOWN_MS: 10000,
    },

    // Skill - Teleport (W)
    SKILL_TELEPORT: {
        MAX_DISTANCE: 400,
        MIN_DISTANCE: 200,
        DAMAGE_RADIUS: 100,
        DAMAGE: 12,
        COOLDOWN_MS: 8000,
    },

    // Skill - Telepathy (E)
    SKILL_TELEPATHY: {
        RADIUS: 180,
        DAMAGE_PER_TICK: 2,
        MAX_HEAL_PER_TICK: 4,
        DURATION_MS: 3000,
        COOLDOWN_MS: 15000,
    },

    // Crazy-Eyes - Wave Attack (기본 공격)
    SKILL_WAVE: {
        RADIUS: 250,
        DAMAGE: 15,
        CONFUSION_DURATION_MS: 3000,    // 혼란 지속 3초
        COOLDOWN_MS: 2000,
    },

    // Crazy-Eyes - Madness Walk (광기 산책)
    SKILL_MADNESS: {
        RADIUS: 150,
        DAMAGE_PER_TICK: 1,             // 틱당 1 데미지 (초당 5)
        DURATION_MS: 5000,
        TICK_INTERVAL_MS: 200,
        COOLDOWN_MS: 10000,
    },

    // Curry-Bear - Pot Smash (냄비 내려치기)
    SKILL_POT_SMASH: {
        DAMAGE: 45,                     // 메인 데미지 (25 → 45)
        SPLASH_DAMAGE: 20,              // 스플래시 데미지 (10 → 20)
        RANGE: 250,                     // 부채꼴 거리 (120 → 250)
        ANGLE: 150,                     // 부채꼴 각도 (90 → 150도)
        SPLASH_RADIUS: 120,             // 스플래시 범위 (80 → 120)
        COOLDOWN_MS: 1500,
    },

    // Curry-Bear - Curry Recovery (카레 회복)
    SKILL_CURRY_RECOVERY: {
        MAX_STORED_DAMAGE: 50,          // 최대 저장 가능한 대미지
        STORE_RATIO: 0.5,               // 받은 대미지의 50% 저장
        COOLDOWN_MS: 8000,
    },

    // Shard
    SHARD: {
        MAX_COUNT: 40,
        INITIAL_COUNT: 20,
        SPAWN_MARGIN: 100,
        COLLECT_DISTANCE: 100,
        RESPAWN_MIN_MS: 3000,
        RESPAWN_VARIANCE_MS: 2000,
    },

    // Dummy
    DUMMY: {
        MAX_HP: 30,
        RESPAWN_DELAY_MS: 5000,
        POSITIONS: [
            { offsetX: 300, offsetY: 0, name: 'Dummy 1' },
            { offsetX: -300, offsetY: 0, name: 'Dummy 2' },
            { offsetX: 0, offsetY: 300, name: 'Dummy 3' },
        ],
    },

    // Chat
    CHAT: {
        MAX_MESSAGE_LENGTH: 200,
    },

    // Rate limiting (in milliseconds)
    RATE_LIMIT: {
        MOVE_MS: 50,                    // 50ms = 초당 20회
        ATTACK_MS: 500,                 // 기본 공격 쿨다운과 동일
        CHAT_MS: 1000,                  // 초당 1회
    },
};

// Computed values
SERVER_CONFIG.PLAYER.MAX_MOVE_DISTANCE_PER_TICK =
    SERVER_CONFIG.PLAYER.SPEED * SERVER_CONFIG.PLAYER.SPEED_TOLERANCE * 0.1;

// Legacy constants for backward compatibility
const GAME_WIDTH = SERVER_CONFIG.WORLD.WIDTH;
const GAME_HEIGHT = SERVER_CONFIG.WORLD.HEIGHT;
const PLAYER_SPEED = SERVER_CONFIG.PLAYER.SPEED;
const PLAYER_SPEED_TOLERANCE = SERVER_CONFIG.PLAYER.SPEED_TOLERANCE;
const ATTACK_POWER = SERVER_CONFIG.COMBAT.ATTACK_POWER;
const ATTACK_RANGE = SERVER_CONFIG.COMBAT.ATTACK_RANGE;
const TELEPORT_MAX_DISTANCE = SERVER_CONFIG.SKILL_TELEPORT.MAX_DISTANCE;
const TELEPORT_DAMAGE_RADIUS = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE_RADIUS;
const TELEPORT_DAMAGE = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE;
const LASER_DAMAGE = SERVER_CONFIG.SKILL_LASER.DAMAGE;
const LASER_MAX_LENGTH = SERVER_CONFIG.SKILL_LASER.MAX_LENGTH;
const TELEPATHY_RADIUS = SERVER_CONFIG.SKILL_TELEPATHY.RADIUS;
const TELEPATHY_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.DAMAGE_PER_TICK;
const TELEPATHY_MAX_HEAL_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.MAX_HEAL_PER_TICK;
const SHARD_COLLECT_DISTANCE = SERVER_CONFIG.SHARD.COLLECT_DISTANCE;
const CHAT_MAX_MESSAGE_LENGTH = SERVER_CONFIG.CHAT.MAX_MESSAGE_LENGTH;
const RATE_LIMIT_MOVE = SERVER_CONFIG.RATE_LIMIT.MOVE_MS;
const RATE_LIMIT_ATTACK = SERVER_CONFIG.RATE_LIMIT.ATTACK_MS;
const RATE_LIMIT_CHAT = SERVER_CONFIG.RATE_LIMIT.CHAT_MS;
const KNOCKBACK_MIN = SERVER_CONFIG.KNOCKBACK.MIN_DISTANCE;
const KNOCKBACK_MAX = SERVER_CONFIG.KNOCKBACK.MAX_DISTANCE;
const KNOCKBACK_MULTIPLIER_MIN = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MIN;
const KNOCKBACK_MULTIPLIER_MAX = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MAX;
const PLAYER_RESPAWN_DELAY = SERVER_CONFIG.PLAYER.RESPAWN_DELAY_MS;
const DUMMY_RESPAWN_DELAY = SERVER_CONFIG.DUMMY.RESPAWN_DELAY_MS;
const WAVE_RADIUS = SERVER_CONFIG.SKILL_WAVE.RADIUS;
const WAVE_DAMAGE = SERVER_CONFIG.SKILL_WAVE.DAMAGE;
const WAVE_CONFUSION_DURATION = SERVER_CONFIG.SKILL_WAVE.CONFUSION_DURATION_MS;
const MADNESS_RADIUS = SERVER_CONFIG.SKILL_MADNESS.RADIUS;
const MADNESS_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_MADNESS.DAMAGE_PER_TICK;
const MADNESS_DURATION = SERVER_CONFIG.SKILL_MADNESS.DURATION_MS;
const MADNESS_TICK_INTERVAL = SERVER_CONFIG.SKILL_MADNESS.TICK_INTERVAL_MS;
const POT_SMASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.DAMAGE;
const POT_SMASH_SPLASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_DAMAGE;
const POT_SMASH_RANGE = SERVER_CONFIG.SKILL_POT_SMASH.RANGE;
const POT_SMASH_ANGLE = SERVER_CONFIG.SKILL_POT_SMASH.ANGLE;
const POT_SMASH_SPLASH_RADIUS = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_RADIUS;
const CURRY_RECOVERY_MAX_STORED = SERVER_CONFIG.SKILL_CURRY_RECOVERY.MAX_STORED_DAMAGE;
const CURRY_RECOVERY_STORE_RATIO = SERVER_CONFIG.SKILL_CURRY_RECOVERY.STORE_RATIO;
const CURRY_RECOVERY_COOLDOWN = SERVER_CONFIG.SKILL_CURRY_RECOVERY.COOLDOWN_MS;

module.exports = {
    SERVER_CONFIG,
    GAME_WIDTH,
    GAME_HEIGHT,
    PLAYER_SPEED,
    PLAYER_SPEED_TOLERANCE,
    ATTACK_POWER,
    ATTACK_RANGE,
    TELEPORT_MAX_DISTANCE,
    TELEPORT_DAMAGE_RADIUS,
    TELEPORT_DAMAGE,
    LASER_DAMAGE,
    LASER_MAX_LENGTH,
    TELEPATHY_RADIUS,
    TELEPATHY_DAMAGE_PER_TICK,
    TELEPATHY_MAX_HEAL_PER_TICK,
    SHARD_COLLECT_DISTANCE,
    CHAT_MAX_MESSAGE_LENGTH,
    RATE_LIMIT_MOVE,
    RATE_LIMIT_ATTACK,
    RATE_LIMIT_CHAT,
    KNOCKBACK_MIN,
    KNOCKBACK_MAX,
    KNOCKBACK_MULTIPLIER_MIN,
    KNOCKBACK_MULTIPLIER_MAX,
    PLAYER_RESPAWN_DELAY,
    DUMMY_RESPAWN_DELAY,
    WAVE_RADIUS,
    WAVE_DAMAGE,
    WAVE_CONFUSION_DURATION,
    MADNESS_RADIUS,
    MADNESS_DAMAGE_PER_TICK,
    MADNESS_DURATION,
    MADNESS_TICK_INTERVAL,
    POT_SMASH_DAMAGE,
    POT_SMASH_SPLASH_DAMAGE,
    POT_SMASH_RANGE,
    POT_SMASH_ANGLE,
    POT_SMASH_SPLASH_RADIUS,
    CURRY_RECOVERY_MAX_STORED,
    CURRY_RECOVERY_STORE_RATIO,
    CURRY_RECOVERY_COOLDOWN,
};
