// ========================================
// SERVER CONFIGURATION
// Extends shared GAME_CONFIG with server-specific settings
// (Anti-cheat: ignore client values, use these)
// ========================================

import { GAME_CONFIG, type GameConfigType } from '../shared/config';

// Server-specific configuration
interface ServerOnlyConfig {
    PLAYER: {
        SPEED_TOLERANCE: number;
    };
    RATE_LIMIT: {
        MOVE_MS: number;
        ATTACK_MS: number;
        CHAT_MS: number;
    };
}

const SERVER_ONLY_CONFIG: ServerOnlyConfig = {
    // Player server-specific settings
    PLAYER: {
        SPEED_TOLERANCE: 1.5, // Allow 50% variance for network latency
    },

    // Rate limiting (in milliseconds) - server-only
    RATE_LIMIT: {
        MOVE_MS: 50, // 50ms = 20 requests per second
        ATTACK_MS: 500, // Same as attack cooldown
        CHAT_MS: 1000, // 1 message per second
    },
};

// Extended server config type
export interface ServerConfigType extends GameConfigType {
    PLAYER: GameConfigType['PLAYER'] & ServerOnlyConfig['PLAYER'] & {
        MAX_MOVE_DISTANCE_PER_TICK: number;
    };
    RATE_LIMIT: ServerOnlyConfig['RATE_LIMIT'];
}

// Merge configurations
export const SERVER_CONFIG: ServerConfigType = {
    // Spread shared config
    ...GAME_CONFIG,

    // Override/extend PLAYER with server-specific settings
    PLAYER: {
        ...GAME_CONFIG.PLAYER,
        ...SERVER_ONLY_CONFIG.PLAYER,
        MAX_MOVE_DISTANCE_PER_TICK: 0, // Will be computed below
    },

    // Add server-only sections
    RATE_LIMIT: SERVER_ONLY_CONFIG.RATE_LIMIT,
};

// Computed values
SERVER_CONFIG.PLAYER.MAX_MOVE_DISTANCE_PER_TICK =
    SERVER_CONFIG.PLAYER.SPEED * SERVER_CONFIG.PLAYER.SPEED_TOLERANCE * 0.1;

// Legacy constants for backward compatibility
export const GAME_WIDTH = SERVER_CONFIG.WORLD.WIDTH;
export const GAME_HEIGHT = SERVER_CONFIG.WORLD.HEIGHT;
export const PLAYER_SPEED = SERVER_CONFIG.PLAYER.SPEED;
export const PLAYER_SPEED_TOLERANCE = SERVER_CONFIG.PLAYER.SPEED_TOLERANCE;
export const ATTACK_POWER = SERVER_CONFIG.COMBAT.ATTACK_POWER;
export const ATTACK_RANGE = SERVER_CONFIG.COMBAT.ATTACK_RANGE;
export const TELEPORT_MAX_DISTANCE = SERVER_CONFIG.SKILL_TELEPORT.MAX_DISTANCE;
export const TELEPORT_DAMAGE_RADIUS = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE_RADIUS;
export const TELEPORT_DAMAGE = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE;
export const LASER_DAMAGE = SERVER_CONFIG.SKILL_LASER.DAMAGE;
export const LASER_MAX_LENGTH = SERVER_CONFIG.SKILL_LASER.MAX_LENGTH;
export const TELEPATHY_RADIUS = SERVER_CONFIG.SKILL_TELEPATHY.RADIUS;
export const TELEPATHY_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.DAMAGE_PER_TICK;
export const TELEPATHY_MAX_HEAL_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.MAX_HEAL_PER_TICK;
export const SHARD_COLLECT_DISTANCE = SERVER_CONFIG.SHARD.COLLECT_DISTANCE;
export const CHAT_MAX_MESSAGE_LENGTH = SERVER_CONFIG.CHAT.MAX_MESSAGE_LENGTH;
export const RATE_LIMIT_MOVE = SERVER_CONFIG.RATE_LIMIT.MOVE_MS;
export const RATE_LIMIT_ATTACK = SERVER_CONFIG.RATE_LIMIT.ATTACK_MS;
export const RATE_LIMIT_CHAT = SERVER_CONFIG.RATE_LIMIT.CHAT_MS;
export const KNOCKBACK_MIN = SERVER_CONFIG.KNOCKBACK.MIN_DISTANCE;
export const KNOCKBACK_MAX = SERVER_CONFIG.KNOCKBACK.MAX_DISTANCE;
export const KNOCKBACK_MULTIPLIER_MIN = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MIN;
export const KNOCKBACK_MULTIPLIER_MAX = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MAX;
export const PLAYER_RESPAWN_DELAY = SERVER_CONFIG.PLAYER.RESPAWN_DELAY_MS;
export const DUMMY_RESPAWN_DELAY = SERVER_CONFIG.DUMMY.RESPAWN_DELAY_MS;
export const WAVE_RADIUS = SERVER_CONFIG.SKILL_WAVE.RADIUS;
export const WAVE_DAMAGE = SERVER_CONFIG.SKILL_WAVE.DAMAGE;
export const WAVE_CONFUSION_DURATION = SERVER_CONFIG.SKILL_WAVE.CONFUSION_DURATION_MS;
export const MADNESS_RADIUS = SERVER_CONFIG.SKILL_MADNESS.RADIUS;
export const MADNESS_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_MADNESS.DAMAGE_PER_TICK;
export const MADNESS_DURATION = SERVER_CONFIG.SKILL_MADNESS.DURATION_MS;
export const MADNESS_TICK_INTERVAL = SERVER_CONFIG.SKILL_MADNESS.TICK_INTERVAL_MS;
export const POT_SMASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.DAMAGE;
export const POT_SMASH_SPLASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_DAMAGE;
export const POT_SMASH_RANGE = SERVER_CONFIG.SKILL_POT_SMASH.RANGE;
export const POT_SMASH_ANGLE = SERVER_CONFIG.SKILL_POT_SMASH.ANGLE;
export const POT_SMASH_SPLASH_RADIUS = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_RADIUS;
export const CURRY_RECOVERY_MAX_STORED = SERVER_CONFIG.SKILL_CURRY_RECOVERY.MAX_STORED_DAMAGE;
export const CURRY_RECOVERY_STORE_RATIO = SERVER_CONFIG.SKILL_CURRY_RECOVERY.STORE_RATIO;
export const CURRY_RECOVERY_COOLDOWN = SERVER_CONFIG.SKILL_CURRY_RECOVERY.COOLDOWN_MS;

// Hulk-Sister constants
export const SPIN_THROW_GRAB_RANGE = SERVER_CONFIG.SKILL_SPIN_THROW.GRAB_RANGE;
export const SPIN_THROW_DISTANCE = SERVER_CONFIG.SKILL_SPIN_THROW.THROW_DISTANCE;
export const SPIN_THROW_DAMAGE = SERVER_CONFIG.SKILL_SPIN_THROW.DAMAGE;
export const SPIN_THROW_COLLISION_DAMAGE = SERVER_CONFIG.SKILL_SPIN_THROW.COLLISION_DAMAGE;
export const RAGE_DURATION = SERVER_CONFIG.SKILL_RAGE.DURATION_MS;
export const RAGE_DAMAGE_MULTIPLIER = SERVER_CONFIG.SKILL_RAGE.DAMAGE_MULTIPLIER;
export const RAGE_THROW_MULTIPLIER = SERVER_CONFIG.SKILL_RAGE.THROW_MULTIPLIER;

// Re-export GAME_CONFIG for consumers that need it
export { GAME_CONFIG };
