// ========================================
// SERVER CONFIGURATION
// Extends shared GAME_CONFIG with server-specific settings
// (Anti-cheat: ignore client values, use these)
// ========================================

const { GAME_CONFIG } = require('../shared/config');

// Server-specific configuration
const SERVER_ONLY_CONFIG = {
    // Player server-specific settings
    PLAYER: {
        SPEED_TOLERANCE: 1.5,           // Allow 50% variance for network latency
    },

    // Rate limiting (in milliseconds) - server-only
    RATE_LIMIT: {
        MOVE_MS: 50,                    // 50ms = 20 requests per second
        ATTACK_MS: 500,                 // Same as attack cooldown
        CHAT_MS: 1000,                  // 1 message per second
    },
};

// Merge configurations
const SERVER_CONFIG = {
    // Spread shared config
    ...GAME_CONFIG,

    // Override/extend PLAYER with server-specific settings
    PLAYER: {
        ...GAME_CONFIG.PLAYER,
        ...SERVER_ONLY_CONFIG.PLAYER,
    },

    // Add server-only sections
    RATE_LIMIT: SERVER_ONLY_CONFIG.RATE_LIMIT,
};

// Computed values
SERVER_CONFIG.PLAYER.MAX_MOVE_DISTANCE_PER_TICK =
    SERVER_CONFIG.PLAYER.SPEED * SERVER_CONFIG.PLAYER.SPEED_TOLERANCE * 0.1;

// Legacy constants for backward compatibility
const GAME_WIDTH = SERVER_CONFIG.WORLD.WIDTH;
const GAME_HEIGHT = SERVER_CONFIG.WORLD.HEIGHT;
const PLAYER_SPEED = SERVER_CONFIG.PLAYER.SPEED;
const PLAYER_SPEED_TOLERANCE = SERVER_CONFIG.PLAYER.SPEED_TOLERANCE;
const ATTACK_POWER = SERVER_CONFIG.COMBAT.ATTACK_POWER;
const ATTACK_RANGE = SERVER_CONFIG.COMBAT.ATTACK_RANGE;
const TELEPORT_MAX_DISTANCE = SERVER_CONFIG.SKILL_TELEPORT.MAX_DISTANCE;
const TELEPORT_DAMAGE_RADIUS = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE_RADIUS;
const TELEPORT_DAMAGE = SERVER_CONFIG.SKILL_TELEPORT.DAMAGE;
const LASER_DAMAGE = SERVER_CONFIG.SKILL_LASER.DAMAGE;
const LASER_MAX_LENGTH = SERVER_CONFIG.SKILL_LASER.MAX_LENGTH;
const TELEPATHY_RADIUS = SERVER_CONFIG.SKILL_TELEPATHY.RADIUS;
const TELEPATHY_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.DAMAGE_PER_TICK;
const TELEPATHY_MAX_HEAL_PER_TICK = SERVER_CONFIG.SKILL_TELEPATHY.MAX_HEAL_PER_TICK;
const SHARD_COLLECT_DISTANCE = SERVER_CONFIG.SHARD.COLLECT_DISTANCE;
const CHAT_MAX_MESSAGE_LENGTH = SERVER_CONFIG.CHAT.MAX_MESSAGE_LENGTH;
const RATE_LIMIT_MOVE = SERVER_CONFIG.RATE_LIMIT.MOVE_MS;
const RATE_LIMIT_ATTACK = SERVER_CONFIG.RATE_LIMIT.ATTACK_MS;
const RATE_LIMIT_CHAT = SERVER_CONFIG.RATE_LIMIT.CHAT_MS;
const KNOCKBACK_MIN = SERVER_CONFIG.KNOCKBACK.MIN_DISTANCE;
const KNOCKBACK_MAX = SERVER_CONFIG.KNOCKBACK.MAX_DISTANCE;
const KNOCKBACK_MULTIPLIER_MIN = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MIN;
const KNOCKBACK_MULTIPLIER_MAX = SERVER_CONFIG.KNOCKBACK.MULTIPLIER_MAX;
const PLAYER_RESPAWN_DELAY = SERVER_CONFIG.PLAYER.RESPAWN_DELAY_MS;
const DUMMY_RESPAWN_DELAY = SERVER_CONFIG.DUMMY.RESPAWN_DELAY_MS;
const WAVE_RADIUS = SERVER_CONFIG.SKILL_WAVE.RADIUS;
const WAVE_DAMAGE = SERVER_CONFIG.SKILL_WAVE.DAMAGE;
const WAVE_CONFUSION_DURATION = SERVER_CONFIG.SKILL_WAVE.CONFUSION_DURATION_MS;
const MADNESS_RADIUS = SERVER_CONFIG.SKILL_MADNESS.RADIUS;
const MADNESS_DAMAGE_PER_TICK = SERVER_CONFIG.SKILL_MADNESS.DAMAGE_PER_TICK;
const MADNESS_DURATION = SERVER_CONFIG.SKILL_MADNESS.DURATION_MS;
const MADNESS_TICK_INTERVAL = SERVER_CONFIG.SKILL_MADNESS.TICK_INTERVAL_MS;
const POT_SMASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.DAMAGE;
const POT_SMASH_SPLASH_DAMAGE = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_DAMAGE;
const POT_SMASH_RANGE = SERVER_CONFIG.SKILL_POT_SMASH.RANGE;
const POT_SMASH_ANGLE = SERVER_CONFIG.SKILL_POT_SMASH.ANGLE;
const POT_SMASH_SPLASH_RADIUS = SERVER_CONFIG.SKILL_POT_SMASH.SPLASH_RADIUS;
const CURRY_RECOVERY_MAX_STORED = SERVER_CONFIG.SKILL_CURRY_RECOVERY.MAX_STORED_DAMAGE;
const CURRY_RECOVERY_STORE_RATIO = SERVER_CONFIG.SKILL_CURRY_RECOVERY.STORE_RATIO;
const CURRY_RECOVERY_COOLDOWN = SERVER_CONFIG.SKILL_CURRY_RECOVERY.COOLDOWN_MS;

// Hulk-Sister constants
const SPIN_THROW_GRAB_RANGE = SERVER_CONFIG.SKILL_SPIN_THROW.GRAB_RANGE;
const SPIN_THROW_DISTANCE = SERVER_CONFIG.SKILL_SPIN_THROW.THROW_DISTANCE;
const SPIN_THROW_DAMAGE = SERVER_CONFIG.SKILL_SPIN_THROW.DAMAGE;
const SPIN_THROW_COLLISION_DAMAGE = SERVER_CONFIG.SKILL_SPIN_THROW.COLLISION_DAMAGE;
const RAGE_DURATION = SERVER_CONFIG.SKILL_RAGE.DURATION_MS;
const RAGE_DAMAGE_MULTIPLIER = SERVER_CONFIG.SKILL_RAGE.DAMAGE_MULTIPLIER;
const RAGE_THROW_MULTIPLIER = SERVER_CONFIG.SKILL_RAGE.THROW_MULTIPLIER;

module.exports = {
    // Re-export GAME_CONFIG for consumers that need it
    GAME_CONFIG,
    SERVER_CONFIG,
    GAME_WIDTH,
    GAME_HEIGHT,
    PLAYER_SPEED,
    PLAYER_SPEED_TOLERANCE,
    ATTACK_POWER,
    ATTACK_RANGE,
    TELEPORT_MAX_DISTANCE,
    TELEPORT_DAMAGE_RADIUS,
    TELEPORT_DAMAGE,
    LASER_DAMAGE,
    LASER_MAX_LENGTH,
    TELEPATHY_RADIUS,
    TELEPATHY_DAMAGE_PER_TICK,
    TELEPATHY_MAX_HEAL_PER_TICK,
    SHARD_COLLECT_DISTANCE,
    CHAT_MAX_MESSAGE_LENGTH,
    RATE_LIMIT_MOVE,
    RATE_LIMIT_ATTACK,
    RATE_LIMIT_CHAT,
    KNOCKBACK_MIN,
    KNOCKBACK_MAX,
    KNOCKBACK_MULTIPLIER_MIN,
    KNOCKBACK_MULTIPLIER_MAX,
    PLAYER_RESPAWN_DELAY,
    DUMMY_RESPAWN_DELAY,
    WAVE_RADIUS,
    WAVE_DAMAGE,
    WAVE_CONFUSION_DURATION,
    MADNESS_RADIUS,
    MADNESS_DAMAGE_PER_TICK,
    MADNESS_DURATION,
    MADNESS_TICK_INTERVAL,
    POT_SMASH_DAMAGE,
    POT_SMASH_SPLASH_DAMAGE,
    POT_SMASH_RANGE,
    POT_SMASH_ANGLE,
    POT_SMASH_SPLASH_RADIUS,
    CURRY_RECOVERY_MAX_STORED,
    CURRY_RECOVERY_STORE_RATIO,
    CURRY_RECOVERY_COOLDOWN,
    SPIN_THROW_GRAB_RANGE,
    SPIN_THROW_DISTANCE,
    SPIN_THROW_DAMAGE,
    SPIN_THROW_COLLISION_DAMAGE,
    RAGE_DURATION,
    RAGE_DAMAGE_MULTIPLIER,
    RAGE_THROW_MULTIPLIER,
};
